theme: jekyll-theme-cayman
title: Disconnettersi
author: Alpha404
Author's home: "https://t.me/alpha4-0-4"
social-network-links:
  email: "someone@example.com"
  telegram: "@disconnettersi"
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
